### ISSUE TITLE
Most devices not going into known_devices.yaml

### ISSUE THREAD

**Issue by SaturnusDJ** [rocket4321/nmap_tracker#5]
Recently had a change which finally enabled me to take away privileged mode from the Home Assistant container. Now it's in a Docker network at 10.2.2.20. The physical network is 192.168.1.0/24.

I found to get nmap_tracker working again, `include_no_mac: true` is needed.

This is the config:
```
  - platform: nmap_tracker
    timeout: 115
    interval_seconds: 120
    consider_home: 210
    hosts: 192.168.1.0/24
    scan_options: "-F"
    exclude_active: false
    include_no_mac: true
    new_device_defaults:
      track_new_devices: true
    debug_log_level: 5
```

It does find the devices that are up, but only the first one (router on 192.168.1.1) is added to `known_devices.yaml`

Replicated this behaviour in a clean HA container with only this component configured.

This is added to `known_devices.yaml`:
```
router_lan:
  name: Router.lan
  mac: XX:XX:XX:XX:XX:XX
  icon:
  picture:
  track: true
```
When renaming the mac to something else, this is added to `known_devices.yaml`:
```
router_lan_2:
  name: Router.lan
  mac: XX:XX:XX:XX:XX:XX
  icon:
  picture:
  track: true
```
So again only the first one.

Did I miss something?
